/**
 * \file
 *
 * \brief Driver ISR.
 *
 *
 * Copyright (C) 2016 Atmel Corporation. All rights reserved.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 *    Atmel microcontroller product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * \asf_license_stop
 *
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include <avr/sleep.h>
#include <util/delay.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/sleep.h>


typedef struct{
	unsigned char second;
	unsigned char minute;
	unsigned char hour;
	unsigned char date;
	unsigned char month;
	unsigned short year;
}time;

time t;


ISR(PORTA_PORT_vect)
{
		if (!(PORTA.IN & (1<<5)))
		{
			sleep_disable();
			DISP_clear();
			LED3_toggle_level();
			PORTA.INTFLAGS = PORT_INT5_bm;
		}
}

ISR(RTC_CNT_vect)
{
		counter();
		char buffer[16];
		char bufmin[16];
		char bufhour[16];
		char bufday[16];
		char bufmonth[16];
		char bufyear[16];
		itoa(t.second,buffer, 10);
		itoa(t.minute,bufmin, 10);
		itoa(t.hour,bufhour, 10);
		itoa(t.date,bufday,10);
		itoa(t.month, bufmonth, 10);
		itoa(t.year, bufyear,10);
		DISP_clear();
		DISP_print(bufhour);
		DISP_print(":");
		DISP_print(bufmin);	
		DISP_print(":");
		DISP_print(buffer);
		DISP_print(" ");
		DISP_print(bufday);
		DISP_print("-");
		DISP_print(bufmonth);
		DISP_print("-");
		DISP_print(bufyear);	
		
	RTC_INTFLAGS = RTC_OVF_bm;
}
